language: python

python:
  - "3.6"

services:
  - xvfb

before_install:
  - sudo apt-get update -qq
  - export DEBIAN_FRONTEND=noninteractive
  - sudo ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
  - sudo DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
  - dpkg-reconfigure --frontend noninteractive tzdata
  - sudo apt-get install -y scilab
  - sudo apt-get install -y r-base python3-dev python3-venv python3-pip python3-setuptools python3-wheel
  - export DISPLAY=:99.0

# command to install dependencies
install:
  - pip3 install -r requirements/requirements-common.txt
  - pip3 install codecov
  - python3 setup.py develop

before_script:
  - python3 manage.py makemigrations
  - python3 manage.py migrate auth
  - python3 manage.py migrate

# command to run tests and coverage
script:
  - coverage erase
  - coverage run -p manage.py test -v 2 yaksh
  - coverage run -p manage.py test -v 2 grades
  - coverage run -p manage.py test -v 2 yaksh.live_server_tests.load_test
  - coverage run -p manage.py test -v 2 api

after_success:
  - coverage combine
  - coverage report
  - codecov

dist:
  bionic

addons:
  firefox: "46.0"
